version: "3.8"

services:
  cassandra1:
    image: cassandra:4.1
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=LabCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra1
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=100M
    ports:
      - "9042:9042"
    networks:
      - cass-net

  cassandra2:
    image: cassandra:4.1
    container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=LabCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_LISTEN_ADDRESS=cassandra2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra2
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=100M
    networks:
      - cass-net

  cassandra3:
    image: cassandra:4.1
    container_name: cassandra3
    environment:
      - CASSANDRA_CLUSTER_NAME=LabCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_LISTEN_ADDRESS=cassandra3
      - CASSANDRA_BROADCAST_ADDRESS=cassandra3
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra3
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=100M
    networks:
      - cass-net

networks:
  cass-net:
    driver: bridge
